# Docker Compose configuration for Snap2Slides development environment
version: '3.8'

services:
  # ===================
  # Main Application
  # ===================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - snap2slides-network
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  # ===================
  # MongoDB Database
  # ===================
  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=snap2slides
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - snap2slides-network
    restart: unless-stopped

  # ===================
  # Redis for Caching
  # ===================
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - snap2slides-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # ===================
  # Nginx Reverse Proxy
  # ===================
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - snap2slides-network
    depends_on:
      - app
    restart: unless-stopped

  # ===================
  # Development Tools
  # ===================
  
  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    networks:
      - snap2slides-network
    depends_on:
      - mongodb
    restart: unless-stopped
    profiles:
      - dev-tools

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - snap2slides-network
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - dev-tools

# ===================
# Networks
# ===================
networks:
  snap2slides-network:
    driver: bridge

# ===================
# Volumes
# ===================
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
